add enhanced docv
smileidentity/smile-identity-core-js pull request #274
Opened 2023-09-27 13:10 UTC by Kennyinspire

This PR aims to add Enhanced Document Verification support to Node.js of the SmileIdentityCore class.

2023-09-29 18:24 UTC, ayinloya commented on examples/enhanced_document_verification.ts
> +  signature: true,
Can we remove this? It is no longer needed

2023-10-02 05:38 UTC, sadick254 requested changes

2023-10-02 05:38 UTC, sadick254 commented on examples/enhanced_document_verification.ts
> +    console.info(result);
```suggestion
    console.info(result);
    return result;
```

2023-10-02 11:12 UTC, ayinloya approved these changes
LGTM

2023-10-02 13:21 UTC, merged